version: "2"

services:
  httprequests: &base
    build: .
    volumes:
      - .:/usr/local/httprequests
  node:
    build:
      context: ./server
    volumes:
      - .:/usr/local/httprequests/server
    ports:
      - "3000:3000"
