version: "2"

services:
  httprequests: &base
    build: .
    volumes:
      - .:/usr/local/httprequests
  node:
    image: "node:8"
    user: "node"
    environment:
      - NODE_ENV=production
    expose:
      - "8081"
    command: "npm start"
